# Alternative GitHub Actions workflow with separate linting job
# This shows how to separate linting from testing for better CI organization

name: Tests with Separate Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    needs: []  # Run independently as fast-fail gate
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python with dependencies (with pip caching)
        uses: ./.github/actions/setup-python-deps
        with:
          python-version: "3.8"
          extras: "dev"
      
      - name: Check code formatting with Black
        run: black --check src/ tests/
      
      - name: Run static analysis with Pylint
        run: pylint src/ tests/
      
      - name: Check import sorting with isort
        run: isort --check-only src/ tests/

  test:
    runs-on: ubuntu-latest
    needs: [lint]  # Wait for lint to pass before running tests
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python with dependencies (with pip caching)
        uses: ./.github/actions/setup-python-deps
        with:
          python-version: ${{ matrix.python-version }}
          extras: "dev"
      
      - name: Run tests with proper imports
        run: |
          # Tests can now use standard absolute imports
          python -m pytest tests/ -v