# Alternative GitHub Actions workflow with separate linting job
# This shows how to separate linting from testing for better CI organization

name: Tests with Separate Linting

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the project in development mode - this eliminates path hacks
          pip install -e ".[dev]"
      
      - name: Run tests with proper imports
        run: |
          # Tests can now use standard absolute imports
          python -m pytest tests/ -v

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the project in development mode for linting
          pip install -e ".[dev]"
      
      - name: Run linting
        run: |
          # Linting runs independently of test matrix
          pylint src/
          black --check src/ tests/
          isort --check-only src/ tests/